In [1]:
import torch

In [17]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x + 2

print(y)

z = y * y * 2
# z = z.mean()
print(z)

tensor([ 0.2719, -0.9629,  0.0890], requires_grad=True)
tensor([2.2719, 1.0371, 2.0890], grad_fn=<AddBackward0>)
tensor([10.3228,  2.1513,  8.7281], grad_fn=<MulBackward0>)


In [13]:
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v) # dz/dx
print(x.grad)

tensor([ 1.0141, -4.1753,  0.0106])


In [21]:
# Prevent gradient tracking?

# x.requires_grad_(False)
# x.detach()
# with torch.no_grad():


tensor([2.2719, 1.0371, 2.0890])


In [25]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights * 3).sum()

    model_output.backward()

    w = weights.grad
    print(w)

    # Important to reset the weights. If we dont do this, the weights will increase by 3 each time.
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
